--- #YAML:1.0
name:                TM-Corpus
version:             0.10
abstract:            Topic Maps, Document Corpus
license:             ~
author:              
    - Robert Barta <drrho@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    BerkeleyDB:                    0.26
    Class::Accessor:               0.3
    Digest::MD5:                   2.36
    File::Path:                    1.08
    File::Temp:                    0.16
    HTML::Entities:                1.35
    LWP:                           2.033
    MLDBM:                         2.01
    Plucene:                       1.24
    Regexp::Common:                2.12
    Regexp::Common::Email::Address: 1.01
    Test::More:                    0.47
    Test::Pod:                     1
    Test::Pod::Coverage:           1.08
    TM:                            1.45
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
