# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         TM-Corpus
version:      0.04
version_from: lib/TM/Corpus.pm
installdirs:  site
requires:
    BerkeleyDB:                    0.26
    Class::Accessor:               0.3
    Digest::MD5:                   2.36
    File::Path:                    1.08
    File::Temp:                    0.16
    HTML::Entities:                1.35
    LWP:                           2.033
    MLDBM:                         2.01
    Plucene:                       1.24
    Test::More:                    0.47
    Test::Pod:                     1
    Test::Pod::Coverage:           1.08
    TM:                            1.33

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
